### ISSUE TITLE
RuntimeError: Could not infer dtype of NoneType

### ISSUE THREAD

**Issue by lx123-j** [seannz/svr#4]
Hello, thank you so much for sharing the code. I've encountered a certain error while running feta3d_svr_test.py. Would you mind providing some guidance on how to resolve it?
Traceback (most recent call last):
  File "/opt/data/private/svr-master/feta3d_svr_test.py", line 57, in <module>
    splat = motion_model.unet3.splat(slices[None, :1], motion.flip(1), mask=slices[None, 1:])
  File "/opt/conda/envs/svr_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/data/private/svr-master/models/flow_UNetS.py", line 194, in forward
    grid = torch.permute(grid, [0] + list(range(2, grid.ndim)) + [1]) * ((torch.tensor(shape, device=x.device) - 1)/(torch.tensor(grid.shape[2:], device=x.device) - 1))
RuntimeError: Could not infer dtype of NoneType

**Comment by seannz** [comment]
Hello @lx123-j 

Yes, you'd need to modify the test script — what are the slice spacing and in-plane resolution of your data? You'd want to ensure the ratio between the two is around 4.

**Comment by lx123-j** [comment]
Thank you very much. Can I use only one 320*320*18 stack with a resolution of 5mm as test data?

**Comment by lx123-j** [comment]
5mm slice spacing.
I noticed in the test data, there's the phrase 'self.label_file = '%s_rec-%s_dseg_reg.nii.gz'. If I'm using my own dataset, do I need to provide the label_file?

**Comment by seannz** [comment]
First, you'd need to re-sample the in-plane resolution to 1.25mm so that the in-plane resolution to slice thickness ratio is 1:4.   The label file just needs to be a foreground mask (which can just be a simple mask of non-zero pixels, for example).

**Comment by lx123-j** [comment]
Thank you very much! I'll give it a try. Do I need to maintain the 1:4 slice spacing ratio? If I were to train a new model, would it also require a 1:4 ratio?

**Comment by seannz** [comment]
Ah, you can change all of these things of course if you're going to be retraining anyway. The ratio really depends on the eventual test cases you'd be working with. In my case, I was targeting mainly 0.8mm:3.0mm – 0.8mm:3.5mm acquisitions, so I chose 1:4 as the ratio.  At test time, I ensure the 1:4 ratio by re-sampling each slice. (For example, the 0.8mm resolution slices above would be resampled to 0.75mm so that 0.75mm:3.0mm = 1:4).

**Comment by lx123-j** [comment]
I see, thank you very much!

**Comment by lx123-j** [comment]
Hello, sorry to bother you. When my image input is transformed into 1.25*1.25*5, with a shape of 272*261*18, and it is input into the `flow = torch.stack([flow[:, d - 2] * ((x.shape[d] - 1)/(flow.shape[d] - 1)) for d in range(2, x.ndim)], 1)` line, the shape of the images will become 1*3*240*16*1, causing the last loop to have a 1 which results in an error, `ZeroDivisionError: division by zero`. Is it because there are too few slices, only 18?

**Comment by seannz** [comment]
The numbers above appear broken (shows as 1.251.255 and 27226118 for me) so I cannot know for sure the exact resolution and shape you are dealing with, but basically in the case of the 1:4 ratio, you'd need to replicate each slice four times before feeding the stack into the network.  Have you been able to run the test script?  You can step through it to see the kind of preprocessing you need to do for your own data.

**Comment by lx123-j** [comment]
Thank you very much for your response. My data has an in-plane resolution of 1.25 and a slice thickness of 5, with dimensions of 272, 261, 18. While running the test script, I observed that during the execution of the code segment `flow = torch.stack([flow[:, d - 2] * ((x.shape[d] - 1)/(flow.shape[d] - 1)) for d in range(2, x.ndim)], 1)`, there is a `ZeroDivisionError: division by zero` error when looping to the fourth dimension because the last dimension is 18. In your response, you mentioned "you'd need to replicate each slice four times before feeding the stack into the network." Does this mean I need to convert the images to 272, 261, 72?

**Comment by seannz** [comment]
Yes, but there are other things like padding etc which will be required as well. So please refer to feta3d_svr_test.py and get your data in the same format.

**Comment by lx123-j** [comment]
ok, thank you very much!

**Comment by lx123-j** [comment]
<img width="734" alt="微信图片_20240517101020" src="https://github.com/seannz/svr/assets/86666427/a64a8639-64f1-4357-91d8-7ca68abdd37c">

Hello,

When I replicated the third dimension of my input image four times to become 72, the reconstruction results were still not satisfactory. What could be the reason for this? Do I need to retrain a model to test it?

Thank you.

**Comment by seannz** [comment]
Is the pre-trained model working on my data? If so, then you should work backwards to see why it doesn't work on your data.

**Comment by seannz** [comment]
Actually, if you can share a link to your data, I *may* be able to have a look into it, as it will be quicker that way.  I can't promise anything, though.

**Comment by lx123-j** [comment]
[MR002962_1102.nii.gz](https://github.com/seannz/svr/files/15345327/MR002962_1102.nii.gz)
[MR002962_1102_mask.nii.gz](https://github.com/seannz/svr/files/15345328/MR002962_1102_mask.nii.gz)
I am able to achieve image reconstruction using the FETA2.2 data, so the issue might be related to my data processing. I would greatly appreciate it if you could take a look at my data to see if reconstruction is possible. I am using the following two Nifti files as test data:
